# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Nikita Kriučkov
title: Quality Assurance Engineer
email: nkriuckov@gmail.com

      +370 618 57509
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  nikitakr
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: findmeoutdoors
linkedin_username: nikitakriuckov
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/prf2.png
about_content: | # this will include new lines to allow paragraphs

  Hi, I am Nikita and I am a beginner in QA field. I already have some experience as a QA specialist and I would like to pursue my career in technology. I am mainly skilled in manual test case preparation, basic QA tools, and bug tracking. Through different work experiences, I have also developed such skills as teamwork, dedication, and analytical thinking, which I believe are beneficial when working as a QA. 
  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Along side my interest for technology I have some other hobbies:

  •	Mastering guitar

  •	Outdoor activities lover

  •	Running enthusiast

  •	Wannabe alpinist with some proven experience in the mountains
    
  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

# Dark mode for the page
darkmode: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
